# This file specifies which version of Nixpkgs we will use.
# It is imported by nix/nixpkgs/default.nix to fetch Nixpkgs.

url = "https://releases.nixos.org/nixos/21.05/nixos-21.05.1076.bad3ccd099e/nixexprs.tar.xz"
sha256 = "05pvil53fhlxj5z20pr100ya83xac998fjw6brn03hpwvpm0h94v"
