[package]
name = "np_text"
version = "0.0.0"
edition = "2018"

[dependencies.libc]
default-features = false
version = "=0.2.98"

[dependencies.np_graphics]
path = "../np_graphics"

[dependencies.np_unix]
path = "../np_unix"

[dependencies.ttf-parser]
default-features = false
version = "=0.12.3"
